#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CMesmesuresOffcial.Resource", IsApplication=true)]

namespace CMesmesuresOffcial
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_close_black_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Smile = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int button1 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int button2 = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int editText1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int editText2 = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int editText3 = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int imageView1 = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int imageView2 = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int imageViewUserPicture = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int mainContent = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ShowYourPicture = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int HomeText1 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int HomeText2 = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int btnContinue = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int btnSignin = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int linkRegister = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
